--- 
framework: mocha
---
postMerge: 
  env: 
    REPONAME: nexe
  pattern: 
    - "./test/**/*.spec.ts"
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
        - docker build --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }} --tag=nucleus
postRun:
     command:
        - node --version
version: 2.0
